MODEL:
  NUM_CLASSES: 21
  META_ARCHITECTURE: 'SSDDetector'
  BOX_PREDICTOR: 'SSDBoxPredictor'
  DEVICE: "cuda"
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval",)
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: '/media/e813/D/weights/SSD_VOC'